apply review changes
MarcoWorms/yfu-contracts pull request #6
Opened 2022-08-18 03:05 UTC by MarcoWorms

closes #2 #3 #4 #5

2022-08-22 08:20 UTC, Majorfi requested changes
Hello @MarcoWorms !
Thank you for the edits, here is a basic review from a non-expert 😬

2022-08-22 08:20 UTC, Majorfi commented on YFUtechne.sol
> +    string public uri = "https://ipfs.io/ipfs/QmSt5CVksdLfvaDCHwPvTGtXs7YrSGcQ2raE3M9nXPifZH/";
I would not set it by default. Best to leave it empty, and populate with constructor maybe

2022-08-22 08:20 UTC, Majorfi commented on YFUtechne.sol
>      }
Maybe add the value for the URI here so we can deploy and set directly based on IPFS deployment

2022-08-22 15:42 UTC, MarcoWorms commented on YFUtechne.sol
>      }
totally agree with the change!

2022-08-24 05:35 UTC, merged

2022-08-24 05:36 UTC, MarcoWorms commented
merged, any other change requests just open an issue!